## Week 3 Model Creation

In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## 2. Load Dataset

In [9]:
df = pd.read_csv("cardio_train.csv", sep=";")

print(df.head())
print("Dataset Shape:", df.shape)

   id    age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0   0  18393       2     168    62.0    110     80            1     1      0   
1   1  20228       1     156    85.0    140     90            3     1      0   
2   2  18857       1     165    64.0    130     70            3     1      0   
3   3  17623       2     169    82.0    150    100            1     1      0   
4   4  17474       1     156    56.0    100     60            1     1      0   

   alco  active  cardio  
0     0       1       0  
1     0       1       1  
2     0       0       1  
3     0       1       1  
4     0       0       0  
Dataset Shape: (70000, 13)


## 3. Data Preprocessing

In [10]:
# Convert age from days to years
df["age"] = (df["age"] / 365).astype(int)

# Calculate BMI
df["BMI"] = df["weight"] / ((df["height"] / 100) ** 2)

# Check missing values
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
BMI            0
dtype: int64


## 4. Select Features and Target

In [11]:
features = [
    "age",
    "height",
    "weight",
    "ap_hi",
    "ap_lo",
    "BMI"
]

X = df[features]
y = df["cardio"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   age  height  weight  ap_hi  ap_lo        BMI
0   50     168    62.0    110     80  21.967120
1   55     156    85.0    140     90  34.927679
2   51     165    64.0    130     70  23.507805
3   48     169    82.0    150    100  28.710479
4   47     156    56.0    100     60  23.011177

Target:
0    0
1    1
2    1
3    1
4    0
Name: cardio, dtype: int64


In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (56000, 6)
Testing Data: (14000, 6)


In [13]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Feature Scaling Completed")

Feature Scaling Completed


In [14]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [15]:
model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed


In [16]:
y_pred = model.predict(X_test)

print("Predictions:")
print(y_pred[:20])

Predictions:
[0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0]


In [17]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.702

Confusion Matrix:
[[5103 1901]
 [2271 4725]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.73      0.71      7004
           1       0.71      0.68      0.69      6996

    accuracy                           0.70     14000
   macro avg       0.70      0.70      0.70     14000
weighted avg       0.70      0.70      0.70     14000



In [18]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.702

Confusion Matrix:
[[5103 1901]
 [2271 4725]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.73      0.71      7004
           1       0.71      0.68      0.69      6996

    accuracy                           0.70     14000
   macro avg       0.70      0.70      0.70     14000
weighted avg       0.70      0.70      0.70     14000



In [19]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset
df = pd.read_csv("cardio_train.csv", sep=";")

# Preprocessing
df["age"] = (df["age"] / 365).astype(int)

# BMI
df["BMI"] = df["weight"] / ((df["height"] / 100) ** 2)

# Features and target
features = [
    "age",
    "height",
    "weight",
    "ap_hi",
    "ap_lo",
    "BMI"
]

X = df[features]
y = df["cardio"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Model
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Training
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("===== LOGISTIC REGRESSION =====")

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

===== LOGISTIC REGRESSION =====
Accuracy: 0.702

Confusion Matrix:
[[5103 1901]
 [2271 4725]]

Classification Report:
              precision    recall  f1-score   support

           0       0.69      0.73      0.71      7004
           1       0.71      0.68      0.69      6996

    accuracy                           0.70     14000
   macro avg       0.70      0.70      0.70     14000
weighted avg       0.70      0.70      0.70     14000



In [20]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("cardio_train.csv", sep=";")

# -----------------------------
# Data Preprocessing
# -----------------------------

# Age: days to years
df["age"] = (df["age"] / 365).astype(int)

# BMI calculation
df["BMI"] = df["weight"] / ((df["height"] / 100) ** 2)

# Features
features = [
    "age",
    "height",
    "weight",
    "ap_hi",
    "ap_lo",
    "BMI"
]

X = df[features].values
y = df["cardio"].values

# -----------------------------
# Normalize Features
# -----------------------------

mean = X.mean(axis=0)
std = X.std(axis=0)

X = (X - mean) / std

# -----------------------------
# Train-Test Split
# -----------------------------

np.random.seed(42)

indices = np.random.permutation(len(X))

train_size = int(0.8 * len(X))

train_indices = indices[:train_size]
test_indices = indices[train_size:]

X_train = X[train_indices]
X_test = X[test_indices]

y_train = y[train_indices]
y_test = y[test_indices]

# -----------------------------
# Add Bias
# -----------------------------

X_train = np.c_[
    np.ones(X_train.shape[0]),
    X_train
]

X_test = np.c_[
    np.ones(X_test.shape[0]),
    X_test
]

# -----------------------------
# Sigmoid Function
# -----------------------------

def sigmoid(z):
    return 1 / (1 + np.exp(-np.clip(z, -500, 500)))


# -----------------------------
# Initialize Weights
# -----------------------------

weights = np.zeros(X_train.shape[1])

learning_rate = 0.01
epochs = 2000

# -----------------------------
# Gradient Descent
# -----------------------------

for epoch in range(epochs):

    # Linear prediction
    z = np.dot(X_train, weights)

    # Sigmoid
    prediction = sigmoid(z)

    # Calculate error
    error = prediction - y_train

    # Gradient
    gradient = np.dot(X_train.T, error) / len(y_train)

    # Update weights
    weights = weights - learning_rate * gradient


# -----------------------------
# Prediction
# -----------------------------

probability = sigmoid(
    np.dot(X_test, weights)
)

# Convert probability to 0 or 1
y_pred = (probability >= 0.5).astype(int)

# -----------------------------
# Accuracy
# -----------------------------

accuracy = np.mean(y_pred == y_test)

print("===== LOGISTIC REGRESSION WITHOUT SKLEARN =====")

print("Accuracy:", accuracy)

print("\nActual Values:")
print(y_test[:20])

print("\nPredicted Values:")
print(y_pred[:20])

===== LOGISTIC REGRESSION WITHOUT SKLEARN =====
Accuracy: 0.6346428571428572

Actual Values:
[0 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0]

Predicted Values:
[1 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0]


NameError: name 'LogisticRegression' is not defined